#165026938 Integrate coveralls code coverage
mirest/stylist-api pull request #7
Opened 2019-04-04 08:10 UTC by RonKbS

#### What does this PR do?
 - It configures the application to allow use of graphQL

#### Description of Task to be completed?
The task requires us to be able to use graphQL queries and mutations.

#### How can this be tested manually?
- Check out to this branch.
- Start the app and run the following query;
```
query{
  users{
    id
    email
    phoneNumber
    isActive
  }
}
```
- Results returned will be similar to those shown in the screenshot

#### Screenshots
<img width="1189" alt="Screenshot 2019-04-04 at 11 06 28" src="https://user-images.githubusercontent.com/40039818/55539676-e14f5a00-56c9-11e9-9dd2-01d9259c3a7b.png">

#### Context
Using the insonmia app to run the query mentioned above

#### Pivotal Tracker Story
- [#165026938](https://www.pivotaltracker.com/story/show/165026938)

2019-04-07 15:59 UTC, kimbugp commented
Please update the piplock and pipfile. 
Run` pipenv install <package to be added> `

2019-04-07 16:09 UTC, kimbugp requested changes

2019-04-07 16:09 UTC, kimbugp commented on requirements.txt
> +pytz==2018.9
Did you install all these packages?

2019-04-07 17:38 UTC, kimbugp commented
Q

2019-04-08 06:39 UTC, RonKbS commented on requirements.txt
> +pytz==2018.9
Yes I did.

2019-04-08 07:33 UTC, kimbugp approved these changes

2019-04-08 07:38 UTC, merged